<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RyberID.Identity.Application\RyberID.Identity.Application.csproj" />
    <ProjectReference Include="..\RyberID.Identity.Domain\RyberID.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fido2" Version="4.0.1" />
    <PackageReference Include="Fido2.AspNet" Version="4.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

</Project>