<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>06f86e85-c5d1-4ff9-9bc7-5dcbefe9c03a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RyberID.Identity.Application\RyberID.Identity.Application.csproj" />
    <ProjectReference Include="..\RyberID.Identity.Infrastructure\RyberID.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>